apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/midnightcrisis/iac-devops-assignment.git
    targetRevision: main
    path: kustomize/overlays/dev
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
